[sources.syslog]
  type = "syslog"
  address = "0.0.0.0:514"
  mode = "tcp"

[sinks.humio]
  type = "humio_logs"
  inputs = ["syslog"]
  healthcheck = true
  token = "${HUMIO_TOKEN}"
  encoding.codec = "json"
  compression = "gzip"
